package com.queuectl.service;

import com.queuectl.model.Config;
import com.queuectl.model.Job;
import com.queuectl.model.JobState;
import com.queuectl.repository.ConfigRepository;
import com.queuectl.repository.JobRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

class JobServiceTest {

    private static final String TEST_DATA_DIR = "./test-service-data";
    private JobService jobService;
    private JobRepository jobRepository;
    private ConfigRepository configRepository;

    @BeforeEach
    void setUp() {
        jobRepository = new JobRepository(TEST_DATA_DIR);
        configRepository = new ConfigRepository(TEST_DATA_DIR);
        jobService = new JobService(jobRepository, configRepository);
    }

    @AfterEach
    void tearDown() throws IOException {
        Path testDir = Path.of(TEST_DATA_DIR);
        if (Files.exists(testDir)) {
            Files.walk(testDir)
                .sorted(Comparator.reverseOrder())
                .map(Path::toFile)
                .forEach(File::delete);
        }
    }

    @Test
    void testEnqueueJobWithAutoGeneratedId() {
        Job job = jobService.enqueueJob(null, "echo test");
        
        assertNotNull(job);
        assertNotNull(job.getId());
        assertEquals("echo test", job.getCommand());
        assertEquals(JobState.PENDING, job.getState());
        assertEquals(0, job.getAttempts());
        assertEquals(3, job.getMaxRetries()); // Default
    }

    @Test
    void testEnqueueJobWithCustomId() {
        Job job = jobService.enqueueJob("custom-id", "echo test");
        
        assertNotNull(job);
        assertEquals("custom-id", job.getId());
        assertEquals("echo test", job.getCommand());
    }

    @Test
    void testEnqueueJobWithEmptyCommand() {
        assertThrows(IllegalArgumentException.class, () -> {
            jobService.enqueueJob(null, "");
        });
    }

    @Test
    void testEnqueueJobWithNullCommand() {
        assertThrows(IllegalArgumentException.class, () -> {
            jobService.enqueueJob(null, null);
        });
    }

    @Test
    void testEnqueueJobWithDuplicateId() {
        jobService.enqueueJob("duplicate-id", "echo test1");
        
        assertThrows(IllegalArgumentException.class, () -> {
            jobService.enqueueJob("duplicate-id", "echo test2");
        });
    }

    @Test
    void testEnqueueJobUsesConfigDefaults() {
        Config config = new Config(5, 3);
        configRepository.save(config);
        
        Job job = jobService.enqueueJob(null, "echo test");
        
        assertEquals(5, job.getMaxRetries());
    }

    @Test
    void testListAllJobs() {
        jobService.enqueueJob("job-1", "cmd1");
        jobService.enqueueJob("job-2", "cmd2");
        jobService.enqueueJob("job-3", "cmd3");
        
        List<Job> jobs = jobService.listJobs(null);
        
        assertEquals(3, jobs.size());
    }

    @Test
    void testListJobsByState() {
        jobService.enqueueJob("job-1", "cmd1");
        jobService.enqueueJob("job-2", "cmd2");
        
        // Manually update one job to completed
        Job job = jobRepository.findById("job-1").get();
        job.setState(JobState.COMPLETED);
        jobRepository.update(job);
        
        List<Job> pendingJobs = jobService.listJobs(JobState.PENDING);
        List<Job> completedJobs = jobService.listJobs(JobState.COMPLETED);
        
        assertEquals(1, pendingJobs.size());
        assertEquals(1, completedJobs.size());
    }

    @Test
    void testGetJobById() {
        jobService.enqueueJob("test-id", "echo test");
        
        Optional<Job> job = jobService.getJobById("test-id");
        
        assertTrue(job.isPresent());
        assertEquals("test-id", job.get().getId());
    }

    @Test
    void testGetDLQJobs() {
        jobService.enqueueJob("job-1", "cmd1");
        jobService.enqueueJob("job-2", "cmd2");
        
        // Move one job to DLQ
        Job job = jobRepository.findById("job-1").get();
        job.setState(JobState.DEAD);
        jobRepository.update(job);
        
        List<Job> dlqJobs = jobService.getDLQJobs();
        
        assertEquals(1, dlqJobs.size());
        assertEquals("job-1", dlqJobs.get(0).getId());
        assertEquals(JobState.DEAD, dlqJobs.get(0).getState());
    }

    @Test
    void testRetryDLQJob() {
        jobService.enqueueJob("failed-job", "exit 1");
        
        // Move to DLQ
        Job job = jobRepository.findById("failed-job").get();
        job.setState(JobState.DEAD);
        job.setAttempts(3);
        jobRepository.update(job);
        
        Job retriedJob = jobService.retryDLQJob("failed-job");
        
        assertEquals(JobState.PENDING, retriedJob.getState());
        assertEquals(0, retriedJob.getAttempts());
        assertNull(retriedJob.getNextRetryAt());
    }

    @Test
    void testRetryDLQJobNotFound() {
        assertThrows(IllegalArgumentException.class, () -> {
            jobService.retryDLQJob("non-existent");
        });
    }

    @Test
    void testRetryDLQJobNotInDLQ() {
        jobService.enqueueJob("pending-job", "echo test");
        
        assertThrows(IllegalArgumentException.class, () -> {
            jobService.retryDLQJob("pending-job");
        });
    }

    @Test
    void testGetStats() {
        // Create jobs in different states
        jobService.enqueueJob("job-1", "cmd1"); // PENDING
        jobService.enqueueJob("job-2", "cmd2"); // PENDING
        jobService.enqueueJob("job-3", "cmd3"); // Will be COMPLETED
        jobService.enqueueJob("job-4", "cmd4"); // Will be FAILED
        jobService.enqueueJob("job-5", "cmd5"); // Will be DEAD
        
        // Update states
        Job job3 = jobRepository.findById("job-3").get();
        job3.setState(JobState.COMPLETED);
        jobRepository.update(job3);
        
        Job job4 = jobRepository.findById("job-4").get();
        job4.setState(JobState.FAILED);
        jobRepository.update(job4);
        
        Job job5 = jobRepository.findById("job-5").get();
        job5.setState(JobState.DEAD);
        jobRepository.update(job5);
        
        JobService.JobStats stats = jobService.getStats();
        
        assertEquals(2, stats.pending);
        assertEquals(0, stats.processing);
        assertEquals(1, stats.completed);
        assertEquals(1, stats.failed);
        assertEquals(1, stats.dead);
    }

    @Test
    void testJobTimestamps() {
        Instant before = Instant.now();
        Job job = jobService.enqueueJob("test-job", "echo test");
        Instant after = Instant.now();
        
        assertNotNull(job.getCreatedAt());
        assertNotNull(job.getUpdatedAt());
        assertTrue(job.getCreatedAt().isAfter(before) || job.getCreatedAt().equals(before));
        assertTrue(job.getCreatedAt().isBefore(after) || job.getCreatedAt().equals(after));
        assertEquals(job.getCreatedAt(), job.getUpdatedAt());
    }
}
